# Generated by Django 5.1 on 2024-11-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_collection',
            field=models.BooleanField(default=False),
        ),
    ]
