# Generated by Django 5.1 on 2024-11-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_top_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_to_home',
            field=models.BooleanField(default=False),
        ),
    ]
