# Generated by Django 5.1 on 2024-09-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_deleted_product_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
    ]
