# Generated by Django 5.1 on 2024-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_color_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
