# Generated by Django 5.1 on 2024-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
