# Generated by Django 5.1 on 2024-12-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_buycart_buycartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_items', to='shop.buycart'),
        ),
    ]
