# Generated by Django 5.1 on 2024-12-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_buycartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buycartitem',
            old_name='cart',
            new_name='buy_cart',
        ),
    ]
