# Generated by Django 5.1 on 2024-12-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_cart_buycartitem_buy_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycartitem',
            name='buy_cart',
        ),
        migrations.RemoveField(
            model_name='buycartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='BuyCart',
        ),
        migrations.DeleteModel(
            name='BuyCartItem',
        ),
    ]
