# Generated by Django 5.1 on 2024-12-05 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_cartitem_created_at_cartitem_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'color', 'size')},
        ),
    ]
