# Generated by Django 5.1 on 2024-12-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_stock_quantity_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
