# Generated by Django 5.1 on 2024-12-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_product_colors_remove_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
