# Generated by Django 5.1 on 2024-12-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_productcolor_remove_productimage_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productcolor'),
        ),
    ]
