# Generated by Django 5.1 on 2024-12-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_attribute_remove_productcolor_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
