# Generated by Django 5.1 on 2024-12-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_attribute_deleted_attributevalue_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='var_title',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='value',
            new_name='var_title',
        ),
    ]
