# Generated by Django 5.1 on 2024-12-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_rename_name_attribute_var_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
