# Generated by Django 5.1 on 2024-12-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_tag_product_has_variants_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
