# Generated by Django 5.1 on 2024-12-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_attributevalue_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='var_title',
        ),
    ]
