# Generated by Django 5.1 on 2024-12-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_rename_name_tag_var_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
