# Generated by Django 5.1 on 2024-12-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='attributes',
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='shop.attribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='shop.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='shop.variant')),
            ],
        ),
    ]
