# Generated by Django 5.1 on 2024-12-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(default=1, upload_to='variants/'),
            preserve_default=False,
        ),
    ]
