# Generated by Django 5.1 on 2024-12-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_productimage_image_alter_variantimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_descriptions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
