# Generated by Django 5.1 on 2024-12-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_product_product_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
