# Generated by Django 5.1 on 2024-12-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_delete_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.CASCADE, to='shop.variant'),
            preserve_default=False,
        ),
    ]
